### ISSUE TITLE
TODO: Conferences to add when I get a sec (or anyone else does)

### ISSUE THREAD

**Issue by chriscoyier** [CSS-Tricks/conferences#12]
- [x] https://smashingconf.com/toronto-2019/
- [x] https://smashingconf.com/freiburg-2019/
- [x] https://smashingconf.com/ny-2019/
- [x] https://2019.jsconf.asia/
- [x] https://www.webdirections.org/design/
- [x] https://www.webdirections.org/code/
- [x] https://www.webdirections.org/wds/
- [x] https://reactfoo.in/2019/
- [x] https://emberconf.com/
- [x] http://us.vuejs.org/
- [x] https://www.reactathon.com/
- [ ] https://jsheroes.io/
- [x] https://reactnewyork.com/
- [x] https://www.yglfconf.com/
- [x] https://cssday.nl/2019
- [x] https://2019.jsconf.us/
- [x] https://2019.dotcss.io/
- [x] https://2019.dotjs.io/
- [x] https://nordicjs.com/

**Comment by Mottie** [comment]
I wonder if https://www.thestrangeloop.com qualifies as a conference that can be listed here?

**Comment by chriscoyier** [comment]
@Mottie in looking at 2018 l didn't seen any session that was particularly front-endy https://www.thestrangeloop.com/2018/sessions.html so I'm gonna say no (even though it looks fun!)
